apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-kbcl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-kbcl
    app.kubernetes.io/part-of: test-backend-clstr
  name: devfile-sample-java-springboot-basic-kbcl
  namespace: psrna-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-kbcl
status:
  loadBalancer: {}
